1. What does Pandas stand for?

Panel Data or Python Data Analysis

2. What are the 2 collections used in Pandas?

    Series and dataFrames

3. Name 4 things Pandas can do for us.

    5 Data Analysis steps:
    Load
    Manipulate
    Prepare
    Model 
    Analyze data

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?

df.sort_values(by='variable, inplace=True)

5. What is a CSV?

    Comma Separated Value - Plain text file format to store number

6. When cleaning data what values do we not like in our data?

    NULL values

In [1]:
#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np
array = np.arange(12)
array_3d = array.reshape(2, 3, 2)
print(array_3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [3]:
#8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
import numpy as np
linear_array = np.linspace(0, 20, 6)
print(linear_array)

#9. Make a Deep Copy of the above array
dc_array = np.copy(linear_array)
dc_array[0] = 69

print(linear_array)
print(dc_array)




[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
[69.  4.  8. 12. 16. 20.]


In [12]:
#10. Concatenate these 3 arrays into a new array named 'newArray'...
 #   ```python
 #           ([[25, 16]])
 #           ([[11, 2], [13, 4]])
 #           ([[7, 81], [5, 6], [11, 12]])

import numpy as np
array_1 = np.array([[25, 16]])
array_2 = np.array([[11, 2], [13, 4]])
array_3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array_1, array_2, array_3), axis=0)
print(newArray)

#11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray, axis=0)
print(sortedArray)

#12. Unpack the array tuples from the above 'sortedArray'  into 4 well named variables. Print the 4 variables.
# Only able to do 2?

a = sortedArray[:, 0]
b = sortedArray[:, 1]
print(a)
print(b)



[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]
[ 5  7 11 11 13 25]
[ 2  4  6 12 16 81]


In [13]:
#13. Combined and sort the following arrays into one called 'comboArray' ...

   # ```python
    #    one = ([10, 11, 12, 13, 14, 15, 16, 17])
     #   two = ([20, 21, 22, 23, 24, 25, 26, 27])
      #  three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    #```

import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))
                            
comboArray = np.sort(comboArray)

print('comboArray', comboArray)

#14.
sec1 = comboArray[1]
sec2 = comboArray[2:]
sec3 = comboArray[3:13]
sec4 = comboArray[-6:]
sec5 = comboArray[:14]
sec6 = comboArray[18::2]
sec7 = comboArray[::-5]

print("sec1:", sec1)
print("sec2:", sec2)
print('sec3:', sec3)
print('sec4:', sec4) 
print('sec5:', sec5)
print('sec6:', sec6)
print('sec7:', sec7)

comboArray [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6: [22 24 26]
sec7: [27 22 15 10  3]


In [25]:
#15. Create a DataFrame using Series
import pandas as pd

recipe = {
    "Ingredients": ["Flour", "Milk", "Eggs", "Spam"],
    "Quantity": [4, 1, 2, 1],
    "Units": ["cups", "cup", "large", "can"]
}

dinner_df = pd.DataFrame(recipe, columns=["Ingredients", "Quantity", "Units"])

print(dinner_df)

  Ingredients  Quantity  Units
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [28]:
#16. Take this data and create a DataFrame named studentData
import pandas as pddata 

data = {

    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)

print(studentData)

#17 add desserts to studentData
desserts = ["Ice cream", "Cashew Fudge", "Waffels", "Carrot Halwa"]
studentData['Desserts'] = desserts

print(studentData)

#18 sort studentData by names and address
sorted_studentData = studentData.sort_values(by=['Name', 'Address'], ascending=[True, True])

print(sorted_studentData)


      Name  Height Qualification  Address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  Address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     Ice cream  
1  Cashew Fudge  
2       Waffels  
3  Carrot Halwa  
      Name  Height Qualification  Address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot        